### ISSUE TITLE
make instance of Data.Map more efficient

### ISSUE THREAD

**Issue by chessai** [chessai/semirings#10]

**Comment by chessai** [comment]
and HashMap

**Comment by Bodigrim** [comment]
Do you have any particular trick in mind? My impression was that these instances are as efficient as possible.

**Comment by chessai** [comment]
If we had a function like

```haskell
mapTimes :: (k -> k -> k) -> (a -> b -> c) -> Map k a -> Map k b -> Map k c
```

It's similar to the spirit of the merge tactics in containers, but allows me to combine keys that are both present. It's sort of like a zipWith/update-keys-as-you-go. I think i could do this if Map had a Biapply instance. That needs QuantifiedConstraints to work, but i'm not sure how i would write it anyway. 

for example, in semirings, we have

```haskell
instance (Ord k, Monoid k, Semiring v) => Semiring (Map k v) where
...
times xs ys = Map.fromListWith (+) [ (mappend k l, v * u) | (k,v) <- Map.toList xs, (l,u) <- Map.toList ys ]
```

Map.fromListWith works fine, but it has to do unnecessary allocations to get the job done. I'd rather only need to accumulate one map.

**Comment by chessai** [comment]
`mapTimes mappend times` would be what i want

**Comment by Bodigrim** [comment]
Well, maps/sets are not proper structures to update-keys-as-you-go. My impression is that iterative modification of keys cost a lot more allocations than `fromList . ... . toList`. For example, even something that simple as `Set.map` is actually nothing but `Set.fromList . List.map f . Set.toList` in disguise.

**Comment by chessai** [comment]
Dang, I think you're right.

Also I looked at the core for some relevant code yesterday and it didn't look that bad.

Closing.
