### ISSUE TITLE
WrappedNum

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#20]
Suppose there is a library `foo` which exports a type `Int42` with `Num` instance. And there is a library `bar`, implementing a function `baz :: Semiring a => a -> a`. The issue is that I cannot feed `Int42` to `baz`, unless I write an orphan instance `Semigroup Int42` (and orphan instances are a pain in maintenance) and repeat all boilerplate definitions.

Can we have a `WrappedNum` newtype? Similar to [WrappedMonad](http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Applicative.html#t:WrappedMonad), [WrappedArrow](http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Applicative.html#t:WrappedArrow) and [WrappedMonoid](http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Semigroup.html#t:WrappedMonoid).

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

import Data.Semiring (Semiring(..))

newtype WrappedNum a = WrappedNum { unWrappedNum :: a }
  deriving (Num)

instance Num a => Semiring (WrappedNum a) where
  zero  = 0
  one   = 1
  plus  = (+)
  times = (*)
```

Returning to my example, such newtype will allow us to apply `baz` to `Int42` without much fuss: `baz (WrappedNum (smth :: Int42))`.

I'll be glad to prepare a PR.

**Comment by chessai** [comment]
Thanks for opening up this issue! I am fine with this. I am at ICFP right
now if you want to say hello. You can implement this if you would like,
otherwise I will do it tonight.

**Comment by chessai** [comment]
If you do make a PR, make sure to include changelog info, and add
documentation on the newtype that it is useful with GHC 8.6+'s
`DerivingVia` extension

**Comment by Bodigrim** [comment]
Have a great conference! Unfortunately I am not there.
