### ISSUE TITLE
(^) is stimes

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#24]
It seems that the definition of `(^)` in `Data.Semiring` matches `stimes`:
```
(^) :: (Semiring a, Integral b) => a -> b -> a
x ^ y = getMul (stimes y (Mul x))
```
As one who has a hand in definitions of `(^)` and `stimes` in `base`, I believe it is worth to consider this implementation to avoid code duplication. This way it will automatically benefit from possible further improvements, new rules and specialisations, defined in `base`.

**Comment by chessai** [comment]
A quick benchmark shows the following:
1. Under `-O2`, your definition is <i>already</i> consistently faster than the current implementation is `semirings`.
2. Under `-O1`, the performance is roughly the same between the two.
3. Under `-O0`, it performs on average worse than the current implementation is in `semirings`.

Here is the code for the benchmark:

```haskell
$ cat Main.hs 
{-# LANGUAGE LambdaCase #-}
{-# OPTIONS_GHC -O0 #-}
--{-# OPTIONS_GHC -O1 #-}
--{-# OPTIONS_GHC -O2 #-}

module Main (main) where

import Control.Applicative (liftA2)
import Data.Semigroup (stimes)
import System.Clock
import Data.Semiring
import Prelude hiding ((^), Num(..))
import Control.Monad (forM)

-- all are greater than 5 to avoid rewrite rules from kicking in
pows :: [Int]
pows = [6,7,8,9,10]

data Pow = One | Two | Three | Four | Five | Six | Seven | Eight
  deriving (Enum)

bases_ :: Pow -> [Int]
bases_ = \case
  One   -> [1..10]
  Two   -> [1..100]
  Three -> [1..1000]
  Four  -> [1..10000]
  Five  -> [1..100000]
  Six   -> [1..1000000]
  Seven -> [1..10000000]
  Eight -> [1..100000000]

bases :: [[Int]]
bases = bases_ <$> [One .. Eight]

main :: IO ()
main = copy >> new

copy :: IO ()
copy = do
  start <- getTime Monotonic
  x <- pure $ forM bases $ \bs -> liftA2 (^) bs pows
  end <- getTime Monotonic
  putStrLn "COPY" 
  putStrLn (showTimeSpec (diffTimeSpec end start))

new :: IO ()
new = do
  start <- getTime Monotonic
  x <- pure $ forM bases $ \bs -> liftA2 newPow bs pows
  end <- getTime Monotonic
  putStrLn "NEW"
  putStrLn (showTimeSpec (diffTimeSpec end start))

newPow :: (Semiring a, Integral b) => a -> b -> a
newPow x y = getMul (stimes y (Mul x))

showTimeSpec :: TimeSpec -> String
showTimeSpec (TimeSpec s ns) =
  show (fromIntegral s + (fromIntegral ns / 1000000000) :: Double)
```

**Comment by chessai** [comment]
I am in favour of this change for the reasons you have stated, and what the benchmarks have shown.

**Comment by chessai** [comment]
Wait, dangit. Those benchmarks are wrong.

Forgot about the allocation of the lists. If you change main's body to be `new >> copy` (flipping them), you get the results backwards. Whichever one is getting the cost of all of the allocations.

**Comment by chessai** [comment]
i should write something with Gauge instead of that hacky script.

**Comment by chessai** [comment]
convinced you are right, committed the change
