### ISSUE TITLE
Commutative vs. associative

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#26]
On several occasions documentation mentions that a semiring comprises of "a commutative monoid and an associative monoid". I believe this statement is worth to be reworded, because it makes a wrong impression that the first monoid is not neccessarily associative. Actually, any monoid is, so "associative monoid" is a tautologism.

**Comment by chessai** [comment]
> On several occasions documentation mentions that a semiring comprises of "a commutative monoid and an associative monoid". I believe this statement is worth to be reworded, because it makes a wrong impression that the first monoid is not neccessarily associative. Actually, any monoid is, so "associative monoid" is a tautologism.

Do you think i should just remove the 'associative' when referring to the multiplicative monoid? So it says 'a commutative monoid' and 'a monoid'?

**Comment by Bodigrim** [comment]
It will be less confusing, yes.

IMHO in the first sentence it is worth to make an emphasis on distributivity, e. g., "a semiring is a set with two operations, connected by distributivity law". And also add a link to wiki, and attach some intuitive examples like "it is plus/times on numbers, or/and on bools, union/intersection on sets".

**Comment by chessai** [comment]
please look at the most recent MASTER, specifically commit e18dcc24f5d69fc1a7fa0d2167ff34d300db2bff.
Let me know what needs improving in the docs w.r.t this issue!

**Comment by chessai** [comment]
Closing - feel free to reopen if you find the new documentation regarding the same issue lacking!

**Comment by Bodigrim** [comment]
Thanks! I left comments to e18dcc2.
