### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#27]
I am gonna use `semirings` in `arithmoi` (https://github.com/cartazio/arithmoi/pull/142), but noticed that `semirings-0.2` is no longer available from Stackage. @chessai do you have any plans to upload it back soon?

**Comment by chessai** [comment]
Well, I never put it on stackage. But, i will today. I'm going to be
working on a lot of my libraries today and this seems like a good starting
point/issue. Thank you for bringing this to my attention

**Comment by Bodigrim** [comment]
`semirings-0.1.3.0` was available from Stackage: https://www.stackage.org/package/semirings/snapshots

**Comment by chessai** [comment]
Strange. Someone else must've put it up. Anyway I'll be putting it up soon.

**Comment by chessai** [comment]
I made a PR for this yesterday! Hasn't been merged yet!

**Comment by chessai** [comment]
https://github.com/commercialhaskell/stackage/pull/4219
