### ISSUE TITLE
Instances for Sum and Product

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#28]
It is kinda confusing that semirings `Sum a` and `Product a` operate similar (matching `a` itself), but `Set (Sum a)` and `Set (Product a)` are different. IMHO it may be beneficial to remove `Semiring` instances for `Sum a` and `Product a`: anyway it is weird to write something like `Sum x * Sum y` or `Product x + Product y`.

Same applies to `Min` / `Max` and `Add` / `Mul`.

**Comment by chessai** [comment]
I agree that the lifting may be unintuitive. I think i am mildly in favour of this, espeically since i have also been irked by Add/Mul, and Sum/Product having * and + operations when they shouldn't.
