### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#34]
As reported by @CarlEdman, `semirings-0.3.1.1` fails to build on Windows:

```
Data\Semiring.hs:144:4: error:
    Module `System.Posix.Types' does not export `CCc'
    |
144 |   (CCc, CDev, CGid, CIno, CMode, CNlink,
    |    ^^^

Data\Semiring.hs:144:15: error:
    Module `System.Posix.Types' does not export `CGid'
    |
144 |   (CCc, CDev, CGid, CIno, CMode, CNlink,
    |               ^^^^

Data\Semiring.hs:144:34: error:
    Module `System.Posix.Types' does not export `CNlink'
    |
144 |   (CCc, CDev, CGid, CIno, CMode, CNlink,
    |                                  ^^^^^^

Data\Semiring.hs:145:16: error:
    Module `System.Posix.Types' does not export `CRLim'
    |
145 |    COff, CPid, CRLim, CSpeed, CSsize,
    |                ^^^^^

Data\Semiring.hs:145:23: error:
    Module `System.Posix.Types' does not export `CSpeed'
    |
145 |    COff, CPid, CRLim, CSpeed, CSsize,
    |                       ^^^^^^

Data\Semiring.hs:146:4: error:
    Module `System.Posix.Types' does not export `CTcflag'
    |
146 |    CTcflag, CUid, Fd)
    |    ^^^^^^^

Data\Semiring.hs:146:13: error:
    Module `System.Posix.Types' does not export `CUid'
    |
146 |    CTcflag, CUid, Fd)
    |             ^^^^
```

I believe I can fix this with CPP, reflecting `#if defined(...)` from `System.Posix.Types`. But do we actually need these instances at all? I doubt that people frequently add UserIDs or multiply GroupIDs. Someone particularly inclined to do so can use `WrappedNum`.

This is reasonably urgent, because it blocks the upcoming `arithmoi` release.

**Comment by chessai** [comment]
because of the urgency, to avoid the need to do a majour release, i'll hide these behind CPP, and worry about the existence of the instances at a later point.

**Comment by chessai** [comment]
@Bodigrim can you try to build semirings with PR #35 on windows? I don't have access to a windows machine.

**Comment by chessai** [comment]
Once I know it builds I will make a release.

**Comment by chessai** [comment]
@CarlEdman pinging you as well, since you're likely to be the one with a windows machine, based on the issue description.

**Comment by Bodigrim** [comment]
It works for me, thanks for rapid patch.

**Comment by chessai** [comment]
Would you like me to go ahead and make the release, or would you rather wait for @CarlEdman to test this as well? AFAIK the brittleness with this CPP is near-zero since we're testing for an operating system and only dealing with a module from base - so i don't really expect a different result from Carl, but i'll defer the decision to you.

**Comment by Bodigrim** [comment]
Please go ahead with release.

**Comment by chessai** [comment]
it is released.

**Comment by Bodigrim** [comment]
Thanks!
