### ISSUE TITLE
Add fields

### ISSUE THREAD

**Issue by masaeedu** [chessai/semirings#36]
We can add another operation here:

```haskell
-- | The class of rings with a multiplicative inverse
--
--     @a '*' 'invert' a = 'one'@
class Ring a => Field a where
  invert :: a -> a
```

This corresponds to division/reciprocal numbers, and can be implemented for e.g. rational numbers and reals.

The overall intuition is that all these structures consist of lawfully interacting pairs of group-like structures. For semirings this is a pair of monoids (one of which is commutative), for rings a commutative group and a monoid, and for fields two commutative groups.

**Comment by chessai** [comment]
I've actually had the same thought, and wanted this several times.

I'll take a PR for this. If there isn't a PR by the time I take up a sudden obsessive interest for 20  minutes, I'll do this

**Comment by chessai** [comment]
A PR should consist of (in Data.Semiring or perhaps another module):

* Adding the `Field` typeclass
* Adding all instances for that typeclass
* documenting the laws of the typeclass
* useful functions acting on types which are instances of the typeclass

**Comment by chessai** [comment]
This is secondary, and not necessary work to be done in `semirings`, but I'd also like `fieldLaws` to be added to quickcheck-classes and hedgehog-classes. (I will do this)

**Comment by chessai** [comment]
Perhaps the name should not be called `invert`? I know it fits, but doesn't mesh well with the popular `groups` package? If there's no better name then I'll yield on that. Note that I'm not worried about name-clashing with the Prelude. Perhaps call it `recip`?

**Comment by chessai** [comment]
Some useful functions that can be defined in terms of recip:

```haskell
a / b = a * recip b
fromRational r = fromInteger (numerator r) / fromInteger (denonimator r)
```

**Comment by chessai** [comment]
Also, not sure what other instances in base there are other than `Float,Double,Ratio,Complex`.

My strategy thus far has been to supply instances for all types in `base` that have relevant instances (here i think that would be `Fractional`). Though, this recently got me into trouble with windows users (see #34)

**Comment by chessai** [comment]
Also, we should probably only allow instances we know to be "traditional". To that end, ratios of functions form a commutative ring (field), so i wonder if we should provide a type/instance for that?

An example of a non-traditional instance would be for a non-field where the density of units is high, e.g. certain residue classes. This high density of units allows the instance to still be useful.

**Comment by Bodigrim** [comment]
> This corresponds to division/reciprocal numbers, and can be implemented for e.g. rational numbers and reals.

We already have `Fractional` for this. Are there any examples of `Field` (in `base`, `containers`, etc.), which are not `Num`? If there are none, I struggle to find a use case for a new type class.

**Comment by Multramate** [comment]
Except for adding `fieldLaws` to `quickcheck-classes` and `hedgehog-classes` (and possibly instances for ratios of functions and non-fields), this issue should be completed with the latest pull request #48.

**Comment by Multramate** [comment]
Will this be released on Hackage anytime soon?

**Comment by chessai** [comment]
Yes, tomorrow

**Comment by Multramate** [comment]
Thanks!

**Comment by chessai** [comment]
this is released. thank you everyone
