### ISSUE TITLE
Implementation of (^) does not match documentation

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#44]
```haskell
-- | Raise a number to a non-negative integral power.
-- If the power is negative, this will return 'zero'.
(^) :: (Semiring a, Integral b) => a -> b -> a
x ^ y = getMul (stimes y (Mul x))
```
In fact it throws an error for negative powers (which is IMO better then returning `zero` - so we need to correct the haddock), but also throws an error for `zero` power (which is unexpected, should be `one`).

_I am on vacation, will prepare a PR next week, if no one picks it up earlier._

**Comment by chessai** [comment]
Ah, this (what's in the docs) was its original behaviour, until the function was changed. I agree we should take on the behaviour you write of.

**Comment by chessai** [comment]
New release contains fix for this.
