### ISSUE TITLE
semiring newtype over Bool

### ISSUE THREAD

**Issue by chessai** [chessai/semirings#45]
@nprindle brought up that the following semiring might be useful:

```haskell
newtype Z = Z { getZ :: Bool }
  deriving stock (Show)
  deriving newtype (Eq, Arbitrary)

instance Semiring Z where
  plus (Z x) (Z y) = Z (x `xor` y)
  times (Z x) (Z y) = Z (x && y)
  zero = Z False
  one = Z True

instance Ring Z where
  negate (Z x) = Z (not x)

instance Star Z where
  star = const 1
```

it is used in computing [Zhegalkin Polynomials](https://en.wikipedia.org/wiki/Zhegalkin_polynomial).

**Comment by Bodigrim** [comment]
This is exactly integers modulo 2. Maybe name it `Mod2`?

**Comment by chessai** [comment]
I think `Zhegalkin` might be better, after the guy who discovered it. Also, it's more googleable.

**Comment by chessai** [comment]
That Ring instance is bad. Don't want to repeat that mistake.

**Comment by Bodigrim** [comment]
Use `negate = id`.

**Comment by chessai** [comment]
actually, `Zhegalkin` might be annoying to type. `Mod2` might therefore be a better name.

**Comment by Bodigrim** [comment]
One more possible name is `newtype Xor`, whatever floats your boat.
