### ISSUE TITLE
missing instances for GcdDomain/Euclidean

### ISSUE THREAD

**Issue by chessai** [chessai/semirings#49]
Only Word and Int have instances. why not {Word|Int}{8,16,32,64}, @Bodigrim?

**Comment by chessai** [comment]
The tests for these (on a branch) fail due to overflow/underflow. I'm leaving them out of the 0.5 release.

**Comment by Bodigrim** [comment]
> Only Word and Int have instances. why not {Word|Int}{8,16,32,64}, @Bodigrim?

Just me being lazy, sorry.

Yep, overflowing would definitely spoil the party. I think it is reasonable to add such instances, probably with a warning that `lcm` may overflow.

**Comment by chessai** [comment]
> > Only Word and Int have instances. why not {Word|Int}{8,16,32,64}, @Bodigrim?
> 
> Just me being lazy, sorry.
> 
> Yep, overflowing would definitely spoil the party. I think it is reasonable to add such instances, probably with a warning that `lcm` may overflow.

Okay, no problem. I was just wondering if there was some obscure thing I didn't understand. We should add these then.

**Comment by Bodigrim** [comment]
Done.

**Comment by chessai** [comment]
Thanks!
