### ISSUE TITLE
Mention RebindableSyntax in haddocks

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#51]
I recently discovered that it is very convenient to enable `{-# LANGUAGE RebindableSyntax #-}` with `semirings`, because it overloads `fromInteger` and `fromRational`, used for desugaring of integer and rational literals, from 
```haskell
fromInteger :: Num a => Integer -> a 
fromRational :: Fractional a => Rational -> a 
```
to
```haskell
fromInteger :: Ring a => Integer -> a 
fromRational :: Field a => Rational -> a 
```
It means that users do not need to replace `0` and `1` by `zero` and `one` anymore.

I think it would be nice to reflect this in the documentation.

**Comment by chessai** [comment]
Oh, i can't believe i never noticed that before! This is great! That would
be a welcome addition to the documentation

**Comment by Bodigrim** [comment]
Done.
