### ISSUE TITLE
Euclidean: Minimal-magnitude quotients break modular arithmetic

### ISSUE THREAD

**Issue by hseg** [chessai/semirings#58]
In ```Prelude```, the difference between ```quot``` and ```div``` is in their choice of rounding behaviour -- ```quot``` rounds towards ```0```, whereas ```div``` rounds to ```-minBound```.
This has the effect of making the output of ```rem``` dependent on the sign of its first input, unlike ```mod```. In particular, ```(`rem` n)``` takes on more than ```n``` values.
Worse, this breaks modular arithmetic: ```(x+y) `rem` n /= ((x `rem` n) + (y `rem` n)) `rem` n```!

But that's Prelude's problem, and the committee's fault for standardizing on a poor default. We can and should do better.

The quick and dirty solution would be to just replace ```quotRem``` by ```divMod```. Better would be to require that ```isJust ((x-y) `divide` m)``` iff ```x `mod` m == y `mod` m```. I don't know if there's an even better solution, but this would at least be a start.

**Comment by chessai** [comment]
Thanks for raising this issue. I will defer to @Bodigrim here

**Comment by Bodigrim** [comment]
From my perspective there are two issues here.

1. I believe that `Euclidean` should not impose more restrictions than its algebraic prototype [Euclidean domain](https://en.wikipedia.org/wiki/Euclidean_domain) does. So both `quotRem` and `divMod`, and even a hypothetical one which maps remainders onto `[-x/2..x/2]` are lawful and acceptable. One is free to define instances for newtypes to obtain a desired behaviour.

2. Which of these instances should be the default one? Even while `divMod` looks more pleasing to my mathematical half, I succumbed to the desire of my engineering half to choose `quotRem` because it is simpler and more efficient on existing hardware.

@hseg How would you implement `instance Euclidean (Complex Integer)`?

**Comment by hseg** [comment]
>From my perspective there are two issues here.
>
>1. I believe that `Euclidean` should not impose more restrictions than
>its algebraic prototype [Euclidean
>domain](https://en.wikipedia.org/wiki/Euclidean_domain) does. So both
>`quotRem` and `divMod`, and even a hypothetical one which maps
>remainders onto `[-x/2..x/2]` are lawful and acceptable. One is free to
>define instances for newtypes to obtain a desired behaviour.
Fair. Indeed, it is difficult to impose any structure on a euclidean domain that would make the choice of representatives unique.

In fact, euclidean domains only seem to be useful as an easy way to show rings are PIDs - the euclidean decomposition isn't usefully unique. Rather, this confusion should be alleviated with a ternary `eqMod`. Of course, those are a harder to make ergonomic.
>2. Which of these instances should be the default one? Even while
>`divMod` looks more pleasing to my mathematical half, I succumbed to
>the desire of my engineering half to choose `quotRem` because it is
>simpler and more efficient on existing hardware.
Fair. I suspect making `divMod` fast isn't hard, just subject to ecosystem inertia

>@hseg How would you implement `instance Euclidean (Complex Integer)`?
Point. (Problem is that Gaussian integers have nontrivially nonunique decomposition)

Toy solution:
```
newtype Modular a = M { modulo :: a → a }
eq :: IntDomain a => a → a → Modular a
-- permits writing (a `eq` b) `modulo` m
```
Opinions?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hseg** [comment]
Of course, that should be `modulo :: Modular a → a → Bool`
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hseg** [comment]
>From my perspective there are two issues here.
>
>1. I believe that `Euclidean` should not impose more restrictions than
>its algebraic prototype [Euclidean
>domain](https://en.wikipedia.org/wiki/Euclidean_domain) does. So both
>`quotRem` and `divMod`, and even a hypothetical one which maps
>remainders onto `[-x/2..x/2]` are lawful and acceptable. One is free to
>define instances for newtypes to obtain a desired behaviour.

Fair. The only problem I have with this argument is that it breaks the natural law that ``a+m*k `mod` m==a `mod` m``. However, if the intent isn't for `rem` to be the map to modular equivalence classes, then arguably we intend for users not be using the actual output of `quotRem` for modular arithmetic at all. Instead, we would want them to use `eqMod :: (IntegralDomain a, Eq a) => a -> a -> a -> Bool` (with a default implementation for `Euclidean a`).

Of course, any such solution would have to deal with the ergonomic problems of ternary operators in Haskell. One such solution could look like:
```
newtype Modular a = M { mod :: a -> Bool }
infix 3 `mod`
eq :: (IntDomain a, Eq a) => a -> a -> Modular a
infix 4 `eq`
-- permits writing a `eq` b `mod` m
```
>2. Which of these instances should be the default one? Even while
>`divMod` looks more pleasing to my mathematical half, I succumbed to
>the desire of my engineering half to choose `quotRem` because it is
>simpler and more efficient on existing hardware.

Fair. I suspect making `divMod` fast isn't hard, just subject to ecosystem inertia

>@hseg How would you implement `instance Euclidean (Complex Integer)`?

Point. Indeed, euclidean division being unique [is equivalent to](https://www.jstor.org/stable/2313196) the norm being submultiplicative (`degree a <= degree (a*b)`) and an "ultranorm" -- i.e. ``degree (a+b) <= degree a `max` degree b``. Submultiplicativity is [easy to dispense with](https://doi.org/10.2307/2316324), but the linked paper shows that a ring has an ultranorm iff it is a polynomial ring over the maximal field it contains.

**Comment by Bodigrim** [comment]
I use http://hackage.haskell.org/package/mod for modular arithmetic.

**Comment by hseg** [comment]
Fair. Looking through my code again, the only reason I really have to care about `Euclidean` is because it's a superclass of `Field`, which while correct litters my code with useless instances.

**Comment by hseg** [comment]
Indeed, by happy coincidence I had decided to unrelatedly replace uses of `Field` by localizations away from a specified element. My code only really needs dyadic integers, so this gives me an exponential memory savings.
Hence, at least for my codebase the question is irrelevant, so it's up to you guys to decide if you want to continue pursuing this. Maybe just adding a line to the effect of "note: `Euclidean` instances are completely free to give different remainders for elements of the same coset, if you want modular arithmetic use <http://hackage.haskell.org/package/mod> instead"?

**Comment by chessai** [comment]
> Indeed, by happy coincidence I had decided to unrelatedly replace uses of `Field` by localizations away from a specified element. My code only really needs dyadic integers, so this gives me an exponential memory savings.
> Hence, at least for my codebase the question is irrelevant, so it's up to you guys to decide if you want to continue pursuing this. Maybe just adding a line to the effect of "note: `Euclidean` instances are completely free to give different remainders for elements of the same coset, if you want modular arithmetic use http://hackage.haskell.org/package/mod instead"?

Sounds reasonable, but I will again defer to @Bodigrim. I don't use the Euclidean interface at all.
