### ISSUE TITLE
implement Monad instance for Poly

### ISSUE THREAD

**Issue by chessai** [chessai/semirings#6]
this can be useful for flattening, because Poly (Poly a) is isomorphic to Poly a.
The notion of collapsing arbitrary polynomials can be implemented via the 'free' package (retract)

**Comment by chessai** [comment]
cannot be done currently, the scheme was previously the following:

```
-- Functor instance is trivial

instance Applicative Poly where
  pure = Poly . Vector.singleton
  Poly f <*> Poly v = Poly $ Vector.zipWith id f v

-- | Horner's scheme for evaluated a polynomial in a semiring
horner :: (Semiring a, Foldable t) => a -> t a -> a
horner x = Foldable.foldr (\c val -> c + x * val) zero

-- | Composition of two polynomials, f(x) and g(x) = f(g(x))
composePoly :: Semiring a => Poly a -> Poly a -> Poly a
composePoly (Poly x) y = horner y (fmap (Poly . Vector.singleton) x)

-- | Collapse nested polynomials, ie collapse f0(f1(f2(...(fn(x))))) into a single function, f
collapse :: Semiring a => Vector (Poly a) -> Poly a
collapse = foldr composePoly zero

-- | polyJoin is <i>nearly</i> 'Control.Monad.join', specialised to Poly
polyJoin :: Semiring a => Poly (Poly a) -> Poly a
polyJoin (Poly x) = collapse x

-- this does not work because bind is universally quantified in 'a' and 'b', 
-- but 'b' /must/ be a semiring.
instance Monad Poly where
  p >>= f = polyJoin (fmap f p)
```

**Comment by chessai** [comment]
cc @andrewthad @mckeankylej any ideas?

**Comment by aljce** [comment]
This isn't possible for the same reason that set cant be a monad. Also that instance of bind would conflict with the `ap = <*>` law. The applicative instance for Poly disallows a monad instance because ZipLists cannot be monads. TLDR no monad instance.

**Comment by chessai** [comment]
Ok, makes sense.

Also you put TLDR for two sentences, lol

**Comment by chessai** [comment]
Polynomials are monads, but not in the context of Hask.
The underlying type requires too strong of a structure (afaik at least a semiring, but possibly a commutative ring) for it to work
