### ISSUE TITLE
Replace CPP instance derivation code with TH/DerivingVia

### ISSUE THREAD

**Issue by hseg** [chessai/semirings#63]
CPP instances as written are less flexible (eg to implement #62 we'd need differing derived instances for the types that are morally integers and those that are morally fields).

Besides, it's ugly, and we have principled alternatives in terms of TH (if we want backwards compatibility) or DerivingVia (supports ghc >=8.6 only, which is two years old).

Am willing to implement this if agreeable.

**Comment by hseg** [comment]
Have sketch of an implementation for `Semiring` based off https://gist.github.com/glguy/0651d4b0b8fb2ab98683788c9b2c39c0#file-multipleinstances-hs, hope to finish it tomorrow. Other classes trivially implementable in this way.
However, solution basically uses the TH inline to avoid staging concerns, which might be ugly to some eyes. If DerivingVia is considered acceptable, it would be preferred.

**Comment by hseg** [comment]
RFC: We currently use CPP for:
* Base instance derivation (this ticket)
* #64 switching between using DerivingVia and TH for base instances
* Specializing `gcdInt` and `gcdWord`
* Hiding use of `MINIMAL` pragmas
* Instance control:
  * `containers`, `unordered_containers`, `Predicate`, `Equivalence`, `Op`,
    `Ap`, Posix types, Generic instances
  * `Data.Data.Data`, `Typeable` instances for `Tropical`

None of these uses seems essential.
* Base instances - see rest of this ticket
* DerivingVia/TH switching can be done by a Backpack-like approach (possibly a
  poor-man's Backpack if the technical burden is scary)
* Idem for the `gcd` implementation switching, modulo cross-module inlining
  concerns
* `MINIMAL` pragmas will be ignored on old GHCs, and don't need guarding
* Instance control admittedly needs CPP, though a restructuring can centralize
  the CPP use. We'd have `Data.Semiring`, `Data.Semiring.Class` and
  `Data.Semiring.Instances.*`, with the individual instance modules controlled
  by Cabal flags and CPPly exported from `Data.Semiring`.
  Such a restructuring could also ease the cycles caused in #65 by putting all
  the classes in `Data.Semiring.Class` and selectively reexporting them from the
  old modules.

Is avoiding CPP desirable enough to put the codebase through this churn?

**Comment by Bodigrim** [comment]
I've been pondering about this and #64 today. Honestly, I do not think that `CPP` is a big deal, at least not in `semirings`. Are there practical reasons to avoid it? Yes, it is not fancy, but it is simple and solid.

IMHO even #64 is a lot of churn. It does not seem that `TemplateHaskell` saves us anything in terms of lines of code. Strategically we would like to use `DerivingVia`, but we need to support older GHCs. This can be achieved by a small change to existing macros, e. g.,

```haskell
#if MIN_VERSION_base(4,12,0)
#define deriveSemiring(ty) \
deriving via (WrappedNum (ty)) instance Semiring (ty)
#else
#define deriveSemiring(ty) \
instance Semiring (ty) where { ... }
#endif
```

**Comment by hseg** [comment]
Fair. Frankly, it's more due to aesthetics than anything else.
This rules out most of my clever ideas to avoid CPP. The only salvageable point here is that to avoid the cyclic imports in #65 we want a `Data.Semiring.Class` module. Other restructuring ideas may be nice on their own rights, but if we're not avoiding CPP they lose a lot of their appeal

**Comment by Bodigrim** [comment]
I guess as long as we support GHC 7.10, we should support the relevant cabal version (which is 1.22) as well.

**Comment by hseg** [comment]
... how long of a support window do we promise to uphold?

**Comment by hseg** [comment]
> Frankly, it's more due to aesthetics than anything else.

At least this issue isn't a total waste -- it has reinforced for me the value of being conservative wrt change for change's sake.

**Comment by Bodigrim** [comment]
> how long of a support window do we promise to uphold?

There is no written policy, but we dropped support of GHC < 7.10 only last month (10ccc770432f7f9aa4acf144dd18a89a74f73ebf). Basically, as long as GHC 7.10 is not causing too much pain, there is not much point to abandon it.
