### ISSUE TITLE
Ord instance is backward?

### ISSUE THREAD

**Issue by danielsmw** [chessai/semirings#69]
I was trying to debug a program and came across the bizarre fact that
```
Tropical 3 > (Infinity :: Tropical Minima Double)
```
evaluates to `True`. Switching `Minima` <--> `Maxima` gives `False`.

However, in the min-plus semiring, `Infinity` must be greater than the finite elements so that it can serve as the additive identity. So it seems that the definition has been reversed, unless I'm missing something stupid.

**Comment by Bodigrim** [comment]
@danielsmw You are right, good catch. Could you possibly raise a PR?
