### ISSUE TITLE
Support window?

### ISSUE THREAD

**Issue by kozross** [chessai/semirings#73]
Based on our Github Actions, we don't seem to support GHCs as far back as the Cabal file claims. We also have CPP for _very_ old versions of GHC (`base-4.6`, which is GHC 7.6 if I remember right).

Is there an official window of support for versions of `base`?

**Comment by chessai** [comment]
Dropping 7.x support is fine. I would prefer it.

**Comment by kozross** [comment]
Cool, I'll send a PR!

**Comment by kozross** [comment]
As mentioned in my (now withdrawn for revision) PR, a few questions arise from the cleanup:

* The instance of `Semiring` for `Complex a` requires a `Ring` instance for `a`. This creates a problem if we move `Ring` to its own module, because now the instance has to be an orphan in `Data.Ring`, as `Data.Ring` _must_ depend on `Data.Semiring` for the `Semiring` superclass on `Ring`. Is there a better way to avoid this? 
* Previously, the `Generics`-based derivations were hidden behind CPP; this is no longer necessary. This led to a bunch of orphan instances for `Ring` being placed there. Should these be adopted by placing the necessary `Generics` machinery into `Data.Ring` and `Data.Semiring`?
* If we move `Ring` to its own module, we can no longer build our tests, as `quickcheck-classes` now fails to build. What should I do about this?

@chessai - could you chime in on these?

**Comment by chessai** [comment]
Perhaps dropping 7.x should come separately from moving Ring into its own module. I forgot about the complex situation around `Complex`. I'm not sure what to do about the situation, I'm inclined to not move anything at all and just deal with the awkward situation of not having a Data.Ring. 

Regarding the Generics-based derivations...what are you referring to exactly? The instances in Data.Semiring.Generic? I think those should be moved to Data.Semiring and just not derived generically. The fact that those are orphans is a mistake on my part.

**Comment by kozross** [comment]
Yes, I did mean exactly Data.Semiring.Generic. I agree that separating out dropping 7.x and `Ring` is the right move, and plan to do it exactly this way.

**Comment by Bodigrim** [comment]
If you proceed with separating `Data.Ring`, I'd appreciate keeping it re-exported from `Data.Semiring` for backward compatibility, at least for some period of time.

**Comment by kozross** [comment]
@Bodigrim That creates a dependency cycle, since by its very definition, `Data.Ring` would have to import `Data.Semiring`. It's a non-trivial concern though, as the current structure is required for at least one package to build sensibly, and we still have a problem with orphan instances for `Complex` if we choose to separate `Ring` into its own module.

**Comment by Bodigrim** [comment]
Ah, right. Well, you can leave `Data.Semiring` as is and re-export `Ring` through `Data.Ring`. This will give downstream dependencies ability to accomodate the change. Then, in the next release actually move `Ring` to `Data.Ring`. 

I'm not really sure how much justified is this. More often than not I need both `Semiring` and `Ring`, and current structure conveniently allows me to write only one import. My resistance to breaking changes apparently comes from having more than one package to migrate :)

**Comment by kozross** [comment]
I'm not strongly wedded to the idea of having `Ring` in a separate module to be honest. I was keen initially, but looking at the details of it, it seems rather more trouble than its worth.
