### ISSUE TITLE
Document list instance

### ISSUE THREAD

**Issue by andreasabel** [chessai/semirings#82]
It is not apparent what the `Semiring` instance for lists is modelling and a comment in the docs would help.
Seems like it considers `repeat zero` equal to `[]`, but this would deserve some explicit comment.

**Comment by chessai** [comment]
Agree

**Comment by chessai** [comment]
Actually, I forgot, but the instances for `[]` were deleted. IIRC they were placeholders for a proper polynomial type, which was not ideal.
